### ISSUE TITLE
Change "Solicitar ayuda" & "Soy centro de acopio" to a more comprehensible CtA

### ISSUE THREAD

**Issue by hecerinc** [sismotec/sismotec-ui#40]
In this screen there are two call to actions if you don't have an account, none of which have anything to do with actually an account.

![sc2](https://user-images.githubusercontent.com/7988472/30993398-77d6cf1c-a474-11e7-8b40-dfbc5abe2257.PNG)

**Comment by melytc** [comment]
Done. Changed in branch ui-register.
It now looks like this:
<img width="292" alt="screen shot 2017-09-28 at 7 36 28 pm" src="https://user-images.githubusercontent.com/8518253/30996178-5a42d4ea-a484-11e7-9f41-1912f36dc24b.png">
